# Generated by Django 5.2.15 on 2026-09-14 05:50

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('category', models.CharField(choices=[('photography', 'Photography'), ('web-development', 'Web Development'), ('video-editing', 'Video Editing'), ('motion-graphics', 'Motion Graphics'), ('graphics-design', 'Graphics Design'), ('others', 'Others')], default='other', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('date_start', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('date_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]