# Generated by Django 5.2.15 on 2026-09-14 05:59

import django.db.models.functions.datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='category',
            field=models.CharField(choices=[('photography', 'Photography'), ('web-development', 'Web Development'), ('video-editing', 'Video Editing'), ('motion-graphics', 'Motion Graphics'), ('graphics-design', 'Graphics Design'), ('others', 'Others')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='date_start',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
