# Generated by Django 5.2.17 on 2026-09-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projects_category_projects_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
